/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is.deb.ui;

import is.deb.gameControl.GameClock;
import is.deb.teams.Team;
import is.ksi.www2.vefthjonustur.mot.ArrayOfFlokkur;
import is.ksi.www2.vefthjonustur.mot.ArrayOfMotStada;
import is.ksi.www2.vefthjonustur.mot.FelogLeikir;
import is.ksi.www2.vefthjonustur.mot.FelogLeikirResponse;
import is.ksi.www2.vefthjonustur.mot.FelogLeikirr;
import is.ksi.www2.vefthjonustur.mot.Flokkur;
import is.ksi.www2.vefthjonustur.mot.FlokkurResponse;
import is.ksi.www2.vefthjonustur.mot.FlokkurSvar;
import is.ksi.www2.vefthjonustur.mot.Flokkurr;
import is.ksi.www2.vefthjonustur.mot.LeikurLeikmennResponse;
import is.ksi.www2.vefthjonustur.mot.MotStadaResponse;
import is.ksi.www2.vefthjonustur.mot.MotStadaSvar;
import is.ksi.www2.vefthjonustur.mot.MotStadaa;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JToggleButton;
import javax.swing.Timer;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 *
 * @author evadoggsteingrimsdottir
 */
public class ScoringUI extends javax.swing.JFrame {
    
    // isGameStarted is false when the application is open for the
    // first time and the value true after btnStartClock is pressed for
    // the first time.
    boolean isGameStarted = false;
    
    GameClock gameClock; 
    GameTimer gameTimer;
    Team homeTeam = new Team();
    Team awayTeam = new Team();
    Team[] teams = new Team[]{homeTeam,awayTeam};
    JLabel[] teamsLabels;
    JToggleButton[] homePlayers;
    JToggleButton[] awayPlayers;
    
    
    

    /**
     * Creates new form ScoringUI
     */
    public ScoringUI() {
        initComponents();
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        teamsLabels = new JLabel[]{labelHomeTeamScore,labelAwayTeamScore};
        homePlayers = new JToggleButton[]{btnHomePlayer0,btnHomePlayer1};
        panelShotActions.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelOverview = new javax.swing.JPanel();
        panelGameClock = new javax.swing.JPanel();
        textFieldClock = new javax.swing.JTextField();
        btnDecreaseTime = new javax.swing.JButton();
        btnStartClock = new javax.swing.JToggleButton();
        btnStopClock = new javax.swing.JToggleButton();
        btnHalfTime = new javax.swing.JToggleButton();
        btnIncreaseTime = new javax.swing.JButton();
        btnTimeOut = new javax.swing.JToggleButton();
        panelHomeTeam = new javax.swing.JPanel();
        labelHomeTeamName = new javax.swing.JLabel();
        labelHomeTeamScore = new javax.swing.JLabel();
        panelAwayTeam = new javax.swing.JPanel();
        labelAwayTeamName = new javax.swing.JLabel();
        labelAwayTeamScore = new javax.swing.JLabel();
        panelHomePlayers = new javax.swing.JPanel();
        btnHomePlayer0 = new javax.swing.JToggleButton();
        btnHomePlayer1 = new javax.swing.JToggleButton();
        btnHomePlayer2 = new javax.swing.JToggleButton();
        btnHomePlayer3 = new javax.swing.JToggleButton();
        btnHomePlayer4 = new javax.swing.JToggleButton();
        btnHomePlayer5 = new javax.swing.JToggleButton();
        btnHomePlayer6 = new javax.swing.JToggleButton();
        btnHomePlayer7 = new javax.swing.JToggleButton();
        btnHomePlayer8 = new javax.swing.JToggleButton();
        btnHomePlayer9 = new javax.swing.JToggleButton();
        btnHomePlayer10 = new javax.swing.JToggleButton();
        btnHomePlayer12 = new javax.swing.JToggleButton();
        btnHomePlayer11 = new javax.swing.JToggleButton();
        btnHomePlayer13 = new javax.swing.JToggleButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelActions = new javax.swing.JPanel();
        btnShot = new javax.swing.JButton();
        btnFoul = new javax.swing.JButton();
        btnAssist = new javax.swing.JButton();
        btnTurnover = new javax.swing.JButton();
        btnThrowIn = new javax.swing.JButton();
        btnCorner = new javax.swing.JButton();
        btnSteal = new javax.swing.JButton();
        btnSevenMeterThrow = new javax.swing.JButton();
        btnFreeThrow = new javax.swing.JButton();
        btnGoalSave = new javax.swing.JButton();
        btnGoalSave1 = new javax.swing.JButton();
        btnGoalSave2 = new javax.swing.JButton();
        btnGoalSave3 = new javax.swing.JButton();
        panelShotActions = new javax.swing.JPanel();
        btnGoal = new javax.swing.JButton();
        btnMiss = new javax.swing.JButton();
        btnShotSaved = new javax.swing.JButton();
        panelAwayPlayers = new javax.swing.JPanel();
        btnAwayPlayer0 = new javax.swing.JToggleButton();
        btnAwayPlayer1 = new javax.swing.JToggleButton();
        btnAwayPlayer2 = new javax.swing.JToggleButton();
        btnAwayPlayer3 = new javax.swing.JToggleButton();
        btnAwayPlayer4 = new javax.swing.JToggleButton();
        btnAwayPlayer5 = new javax.swing.JToggleButton();
        btnAwayPlayer6 = new javax.swing.JToggleButton();
        btnAwayPlayer7 = new javax.swing.JToggleButton();
        btnAwayPlayer8 = new javax.swing.JToggleButton();
        btnAwayPlayer9 = new javax.swing.JToggleButton();
        btnAwayPlayer10 = new javax.swing.JToggleButton();
        btnAwayPlayer11 = new javax.swing.JToggleButton();
        btnAwayPlayer12 = new javax.swing.JToggleButton();
        btnAwayPlayer13 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelOverview.setBackground(new java.awt.Color(102, 255, 255));
        panelOverview.setLayout(new java.awt.GridBagLayout());

        panelGameClock.setBackground(new java.awt.Color(255, 255, 102));

        textFieldClock.setEditable(false);
        textFieldClock.setBackground(new java.awt.Color(255, 102, 204));
        textFieldClock.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        textFieldClock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldClock.setText("00:00");

        btnDecreaseTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecreaseTimeActionPerformed(evt);
            }
        });

        btnStartClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartClockActionPerformed(evt);
            }
        });

        btnStopClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopClockActionPerformed(evt);
            }
        });

        btnHalfTime.setText("Hálfleikur");
        btnHalfTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHalfTimeActionPerformed(evt);
            }
        });

        btnIncreaseTime.setPreferredSize(new java.awt.Dimension(97, 29));
        btnIncreaseTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncreaseTimeActionPerformed(evt);
            }
        });

        btnTimeOut.setText("Leikhlé");
        btnTimeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGameClockLayout = new javax.swing.GroupLayout(panelGameClock);
        panelGameClock.setLayout(panelGameClockLayout);
        panelGameClockLayout.setHorizontalGroup(
            panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameClockLayout.createSequentialGroup()
                .addGroup(panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGameClockLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textFieldClock, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDecreaseTime, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIncreaseTime, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(btnStartClock, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGameClockLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnHalfTime, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStopClock, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelGameClockLayout.setVerticalGroup(
            panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameClockLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGameClockLayout.createSequentialGroup()
                        .addGroup(panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHalfTime, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(textFieldClock, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGameClockLayout.createSequentialGroup()
                        .addComponent(btnIncreaseTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDecreaseTime, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnStopClock, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnStartClock, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 71, 0, 0);
        panelOverview.add(panelGameClock, gridBagConstraints);

        panelHomeTeam.setBackground(new java.awt.Color(51, 102, 255));
        panelHomeTeam.setPreferredSize(new java.awt.Dimension(151, 38));

        labelHomeTeamName.setPreferredSize(new java.awt.Dimension(119, 26));

        labelHomeTeamScore.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelHomeTeamScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelHomeTeamLayout = new javax.swing.GroupLayout(panelHomeTeam);
        panelHomeTeam.setLayout(panelHomeTeamLayout);
        panelHomeTeamLayout.setHorizontalGroup(
            panelHomeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelHomeTeamName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
            .addComponent(labelHomeTeamScore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHomeTeamLayout.setVerticalGroup(
            panelHomeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeTeamLayout.createSequentialGroup()
                .addComponent(labelHomeTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHomeTeamScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(275, 275, 275))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 151;
        gridBagConstraints.ipady = 142;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 9, 0, 0);
        panelOverview.add(panelHomeTeam, gridBagConstraints);

        panelAwayTeam.setBackground(new java.awt.Color(51, 255, 51));
        panelAwayTeam.setPreferredSize(new java.awt.Dimension(151, 38));

        labelAwayTeamScore.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelAwayTeamScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelAwayTeamLayout = new javax.swing.GroupLayout(panelAwayTeam);
        panelAwayTeam.setLayout(panelAwayTeamLayout);
        panelAwayTeamLayout.setHorizontalGroup(
            panelAwayTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAwayTeamName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelAwayTeamScore, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );
        panelAwayTeamLayout.setVerticalGroup(
            panelAwayTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAwayTeamLayout.createSequentialGroup()
                .addComponent(labelAwayTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAwayTeamScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 151;
        gridBagConstraints.ipady = 141;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 80, 0, 0);
        panelOverview.add(panelAwayTeam, gridBagConstraints);

        btnHomePlayer0.setText("Kalli Flotti Jóns (1)");
        btnHomePlayer0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer0ActionPerformed(evt);
            }
        });

        btnHomePlayer1.setText("Siggi Flotti Jóns (2)");
        btnHomePlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer1ActionPerformed(evt);
            }
        });

        btnHomePlayer2.setText("Siggi Flotti Jóns (3)");
        btnHomePlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer2ActionPerformed(evt);
            }
        });

        btnHomePlayer3.setText("Siggi Flotti Jóns (4)");
        btnHomePlayer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer3ActionPerformed(evt);
            }
        });

        btnHomePlayer4.setText("Siggi Flotti Jóns (5)");
        btnHomePlayer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer4ActionPerformed(evt);
            }
        });

        btnHomePlayer5.setText("Siggi Flotti Jóns (6)");
        btnHomePlayer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer5ActionPerformed(evt);
            }
        });

        btnHomePlayer6.setText("Siggi Flotti Jóns (7)");
        btnHomePlayer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer6ActionPerformed(evt);
            }
        });

        btnHomePlayer7.setText("Siggi Flotti Jóns (8)");
        btnHomePlayer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer7ActionPerformed(evt);
            }
        });

        btnHomePlayer8.setText("Siggi Flotti Jóns (9)");
        btnHomePlayer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer8ActionPerformed(evt);
            }
        });

        btnHomePlayer9.setText("Siggi Flotti Jóns (10)");
        btnHomePlayer9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer9ActionPerformed(evt);
            }
        });

        btnHomePlayer10.setText("Siggi Flotti Jóns (11)");
        btnHomePlayer10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer10ActionPerformed(evt);
            }
        });

        btnHomePlayer12.setText("Siggi Flotti Jóns (13)");
        btnHomePlayer12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer12ActionPerformed(evt);
            }
        });

        btnHomePlayer11.setText("Siggi Flotti Jóns (12)");
        btnHomePlayer11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer11ActionPerformed(evt);
            }
        });

        btnHomePlayer13.setText("Siggi Flotti Jóns (14)");
        btnHomePlayer13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer13ActionPerformed(evt);
            }
        });

        jLayeredPane1.setBackground(new java.awt.Color(255, 51, 0));

        panelActions.setBackground(new java.awt.Color(255, 51, 102));

        btnShot.setText("Skot");
        btnShot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShotActionPerformed(evt);
            }
        });

        btnFoul.setText("Brot");
        btnFoul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoulActionPerformed(evt);
            }
        });

        btnAssist.setText("Stoðsending");
        btnAssist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssistActionPerformed(evt);
            }
        });

        btnTurnover.setText("Tapaður bolti");
        btnTurnover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnoverActionPerformed(evt);
            }
        });

        btnThrowIn.setText("Innkast");
        btnThrowIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThrowInActionPerformed(evt);
            }
        });

        btnCorner.setText("Horn");
        btnCorner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCornerActionPerformed(evt);
            }
        });

        btnSteal.setText("Stolinn bolti");
        btnSteal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStealActionPerformed(evt);
            }
        });

        btnSevenMeterThrow.setText("Víti");
        btnSevenMeterThrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenMeterThrowActionPerformed(evt);
            }
        });

        btnFreeThrow.setText("Aukakast");
        btnFreeThrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFreeThrowActionPerformed(evt);
            }
        });

        btnGoalSave.setText("Varið");
        btnGoalSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoalSaveActionPerformed(evt);
            }
        });

        btnGoalSave1.setText("Gult spjald");
        btnGoalSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoalSave1ActionPerformed(evt);
            }
        });

        btnGoalSave2.setText("Rautt spjald");
        btnGoalSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoalSave2ActionPerformed(evt);
            }
        });

        btnGoalSave3.setText("2 mín");
        btnGoalSave3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoalSave3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActionsLayout = new javax.swing.GroupLayout(panelActions);
        panelActions.setLayout(panelActionsLayout);
        panelActionsLayout.setHorizontalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGoalSave3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelActionsLayout.createSequentialGroup()
                        .addComponent(btnGoalSave, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGoalSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnGoalSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelActionsLayout.createSequentialGroup()
                        .addComponent(btnFoul, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTurnover, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnSteal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelActionsLayout.createSequentialGroup()
                        .addComponent(btnShot, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSevenMeterThrow, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFreeThrow, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelActionsLayout.createSequentialGroup()
                        .addComponent(btnAssist, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThrowIn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnCorner, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelActionsLayout.setVerticalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShot, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSevenMeterThrow, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFreeThrow, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFoul, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTurnover, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSteal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssist, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThrowIn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCorner, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGoalSave, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoalSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoalSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGoalSave3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        panelShotActions.setBackground(new java.awt.Color(204, 0, 204));

        btnGoal.setText("Mark");
        btnGoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoalActionPerformed(evt);
            }
        });

        btnMiss.setText("Framhjá");
        btnMiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissActionPerformed(evt);
            }
        });

        btnShotSaved.setText("Varið");
        btnShotSaved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShotSavedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelShotActionsLayout = new javax.swing.GroupLayout(panelShotActions);
        panelShotActions.setLayout(panelShotActionsLayout);
        panelShotActionsLayout.setHorizontalGroup(
            panelShotActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShotActionsLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(panelShotActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShotSaved, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        panelShotActionsLayout.setVerticalGroup(
            panelShotActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShotActionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnShotSaved, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(475, 475, 475))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelShotActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(panelActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(panelShotActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 54, Short.MAX_VALUE)))
        );
        jLayeredPane1.setLayer(panelActions, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panelShotActions, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnAwayPlayer0.setText("Kalli Flotti Jóns (1)");
        btnAwayPlayer0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer0ActionPerformed(evt);
            }
        });

        btnAwayPlayer1.setText("Siggi Flotti Jóns (2)");
        btnAwayPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer1ActionPerformed(evt);
            }
        });

        btnAwayPlayer2.setText("Siggi Flotti Jóns (3)");
        btnAwayPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer2ActionPerformed(evt);
            }
        });

        btnAwayPlayer3.setText("Siggi Flotti Jóns (4)");
        btnAwayPlayer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer3ActionPerformed(evt);
            }
        });

        btnAwayPlayer4.setText("Siggi Flotti Jóns (5)");
        btnAwayPlayer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer4ActionPerformed(evt);
            }
        });

        btnAwayPlayer5.setText("Siggi Flotti Jóns (6)");
        btnAwayPlayer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer5ActionPerformed(evt);
            }
        });

        btnAwayPlayer6.setText("Siggi Flotti Jóns (7)");
        btnAwayPlayer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer6ActionPerformed(evt);
            }
        });

        btnAwayPlayer7.setText("Siggi Flotti Jóns (8)");
        btnAwayPlayer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer7ActionPerformed(evt);
            }
        });

        btnAwayPlayer8.setText("Siggi Flotti Jóns (9)");
        btnAwayPlayer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer8ActionPerformed(evt);
            }
        });

        btnAwayPlayer9.setText("Siggi Flotti Jóns (10)");
        btnAwayPlayer9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer9ActionPerformed(evt);
            }
        });

        btnAwayPlayer10.setText("Siggi Flotti Jóns (11)");
        btnAwayPlayer10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer10ActionPerformed(evt);
            }
        });

        btnAwayPlayer11.setText("Siggi Flotti Jóns (13)");
        btnAwayPlayer11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer11ActionPerformed(evt);
            }
        });

        btnAwayPlayer12.setText("Siggi Flotti Jóns (12)");
        btnAwayPlayer12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer12ActionPerformed(evt);
            }
        });

        btnAwayPlayer13.setText("Siggi Flotti Jóns (14)");
        btnAwayPlayer13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAwayPlayersLayout = new javax.swing.GroupLayout(panelAwayPlayers);
        panelAwayPlayers.setLayout(panelAwayPlayersLayout);
        panelAwayPlayersLayout.setHorizontalGroup(
            panelAwayPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAwayPlayersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelAwayPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAwayPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer0, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer13, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelAwayPlayersLayout.setVerticalGroup(
            panelAwayPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAwayPlayersLayout.createSequentialGroup()
                .addComponent(btnAwayPlayer0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelHomePlayersLayout = new javax.swing.GroupLayout(panelHomePlayers);
        panelHomePlayers.setLayout(panelHomePlayersLayout);
        panelHomePlayersLayout.setHorizontalGroup(
            panelHomePlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomePlayersLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelHomePlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHomePlayer12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer13, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer0, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAwayPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHomePlayersLayout.setVerticalGroup(
            panelHomePlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(panelHomePlayersLayout.createSequentialGroup()
                .addGroup(panelHomePlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomePlayersLayout.createSequentialGroup()
                        .addComponent(btnHomePlayer0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnHomePlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnHomePlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnHomePlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnHomePlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnHomePlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnHomePlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnHomePlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnHomePlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnHomePlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnHomePlayer10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnHomePlayer11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnHomePlayer12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnHomePlayer13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelAwayPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 280, Short.MAX_VALUE))
        );

        jTextField1.setText("jTextField1");

        jMenu1.setText("File");
        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(panelHomePlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 831, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(panelOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelHomePlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHalfTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHalfTimeActionPerformed
        gameTimer.timer.stop();
    }//GEN-LAST:event_btnHalfTimeActionPerformed

    private void btnStartClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartClockActionPerformed

        updateClock();

    }//GEN-LAST:event_btnStartClockActionPerformed

    private void btnStopClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopClockActionPerformed
        gameTimer.timer.stop();
        
        
    }//GEN-LAST:event_btnStopClockActionPerformed

    private void btnDecreaseTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecreaseTimeActionPerformed
        changeGameClock("decrease");
    }//GEN-LAST:event_btnDecreaseTimeActionPerformed

    private void btnTimeOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeOutActionPerformed
        timeout();
    }//GEN-LAST:event_btnTimeOutActionPerformed

    private void btnIncreaseTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncreaseTimeActionPerformed
        changeGameClock("increase");
    }//GEN-LAST:event_btnIncreaseTimeActionPerformed

    private void btnGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoalActionPerformed
        goalScored(0);
    }//GEN-LAST:event_btnGoalActionPerformed

    private void btnHomePlayer0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer0ActionPerformed
        setCurrentPlayer(0);
    }//GEN-LAST:event_btnHomePlayer0ActionPerformed

    private void btnHomePlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer1ActionPerformed
        setCurrentPlayer(1);
    }//GEN-LAST:event_btnHomePlayer1ActionPerformed

    private void btnHomePlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomePlayer2ActionPerformed

    private void btnHomePlayer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomePlayer3ActionPerformed

    private void btnHomePlayer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomePlayer4ActionPerformed

    private void btnHomePlayer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomePlayer5ActionPerformed

    private void btnHomePlayer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomePlayer6ActionPerformed

    private void btnHomePlayer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomePlayer7ActionPerformed

    private void btnHomePlayer8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomePlayer8ActionPerformed

    private void btnHomePlayer9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomePlayer9ActionPerformed

    private void btnHomePlayer10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomePlayer10ActionPerformed

    private void btnHomePlayer11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomePlayer11ActionPerformed

    private void btnHomePlayer12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomePlayer12ActionPerformed

    private void btnHomePlayer13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomePlayer13ActionPerformed

    private void btnAwayPlayer0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAwayPlayer0ActionPerformed

    private void btnAwayPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAwayPlayer1ActionPerformed

    private void btnAwayPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAwayPlayer2ActionPerformed

    private void btnAwayPlayer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAwayPlayer3ActionPerformed

    private void btnAwayPlayer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAwayPlayer4ActionPerformed

    private void btnAwayPlayer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAwayPlayer5ActionPerformed

    private void btnAwayPlayer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAwayPlayer6ActionPerformed

    private void btnAwayPlayer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAwayPlayer7ActionPerformed

    private void btnAwayPlayer8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAwayPlayer8ActionPerformed

    private void btnAwayPlayer9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAwayPlayer9ActionPerformed

    private void btnAwayPlayer10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAwayPlayer10ActionPerformed

    private void btnAwayPlayer11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAwayPlayer11ActionPerformed

    private void btnAwayPlayer12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAwayPlayer12ActionPerformed

    private void btnAwayPlayer13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAwayPlayer13ActionPerformed

    private void btnShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShotActionPerformed
        panelActions.setVisible(false);
        panelShotActions.setVisible(true);  
    }//GEN-LAST:event_btnShotActionPerformed

    
    private void btnFoulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFoulActionPerformed

    private void btnAssistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssistActionPerformed

    private void btnTurnoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTurnoverActionPerformed

    private void btnThrowInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThrowInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThrowInActionPerformed

    private void btnCornerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCornerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCornerActionPerformed

    private void btnStealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStealActionPerformed

    private void btnSevenMeterThrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenMeterThrowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSevenMeterThrowActionPerformed

    private void btnFreeThrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFreeThrowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFreeThrowActionPerformed

    private void btnMissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMissActionPerformed

    private void btnShotSavedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShotSavedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShotSavedActionPerformed

    private void btnGoalSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoalSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoalSaveActionPerformed

    private void btnGoalSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoalSave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoalSave1ActionPerformed

    private void btnGoalSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoalSave2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoalSave2ActionPerformed

    private void btnGoalSave3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoalSave3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoalSave3ActionPerformed

    public void setCurrentPlayer(int buttonPosition) {
        for(int i = 0; i<homePlayers.length; i++) {
            if(homePlayers[i].isSelected()) {
                homePlayers[i].setSelected(false);
            }
        }
        homePlayers[buttonPosition].setSelected(true);
    }
    public void goalScored(int team) {
        teams[team].goalScored(getGoalScorer(team));
        teamsLabels[team].setText(teams[team].getScore()+"");
        //textArea.setText(homeTeam.getGoalScorer()+"");
    } 
    
    public int getGoalScorer(int team) {
        if(team==0) {
            return findScorer(homePlayers, homeTeam);
        }
        else {
            return findScorer(awayPlayers, awayTeam);
        }
    }
    
    public int findScorer(JToggleButton[] buttonTeam, Team team ) {
        for(int i = 0; i<buttonTeam.length; i++) {
            if(buttonTeam[i].isSelected()) {
                int numberinArray = i;
                return team.getPlayerNum(i);
            }
        }
        
        return -1;
    }
    
    public void timeout() {
        if(btnTimeOut.isSelected()) {
            gameTimer.timer.stop();
        }
        else {
            gameTimer.timer.start();
        }
    }
    private void changeGameClock(String action) {
        if("decrease".equals(action)) {
            gameClock.decreaseSeconds();
        }
        else {
            gameClock.increaseSeconds();
        }
        textFieldClock.setText(gameClock.getGameTimeString());
    }
    
    public void updateClock() {
        if(!isGameStarted) {
            gameClock = new GameClock();
            isGameStarted = true;
            gameTimer = new GameTimer();
        }
        gameTimer.timer.start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoringUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoringUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoringUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoringUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoringUI().setVisible(true);
                
                
            }
        });
    }
    
    /**
     * 
     */
    public class GameTimer {
        private final Timer timer; 
        /**
         * 
         */
        public GameTimer() {
            timer = new Timer(1000, new TimerListener());
            timer.start();
        }
        
        /**
         * 
         */
        private class TimerListener implements ActionListener {
            @Override
            public void actionPerformed(ActionEvent e) {
                gameClock.increaseSeconds();
                textFieldClock.setText(gameClock.getGameTimeString());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssist;
    private javax.swing.JToggleButton btnAwayPlayer0;
    private javax.swing.JToggleButton btnAwayPlayer1;
    private javax.swing.JToggleButton btnAwayPlayer10;
    private javax.swing.JToggleButton btnAwayPlayer11;
    private javax.swing.JToggleButton btnAwayPlayer12;
    private javax.swing.JToggleButton btnAwayPlayer13;
    private javax.swing.JToggleButton btnAwayPlayer2;
    private javax.swing.JToggleButton btnAwayPlayer3;
    private javax.swing.JToggleButton btnAwayPlayer4;
    private javax.swing.JToggleButton btnAwayPlayer5;
    private javax.swing.JToggleButton btnAwayPlayer6;
    private javax.swing.JToggleButton btnAwayPlayer7;
    private javax.swing.JToggleButton btnAwayPlayer8;
    private javax.swing.JToggleButton btnAwayPlayer9;
    private javax.swing.JButton btnCorner;
    private javax.swing.JButton btnDecreaseTime;
    private javax.swing.JButton btnFoul;
    private javax.swing.JButton btnFreeThrow;
    private javax.swing.JButton btnGoal;
    private javax.swing.JButton btnGoalSave;
    private javax.swing.JButton btnGoalSave1;
    private javax.swing.JButton btnGoalSave2;
    private javax.swing.JButton btnGoalSave3;
    private javax.swing.JToggleButton btnHalfTime;
    private javax.swing.JToggleButton btnHomePlayer0;
    private javax.swing.JToggleButton btnHomePlayer1;
    private javax.swing.JToggleButton btnHomePlayer10;
    private javax.swing.JToggleButton btnHomePlayer11;
    private javax.swing.JToggleButton btnHomePlayer12;
    private javax.swing.JToggleButton btnHomePlayer13;
    private javax.swing.JToggleButton btnHomePlayer2;
    private javax.swing.JToggleButton btnHomePlayer3;
    private javax.swing.JToggleButton btnHomePlayer4;
    private javax.swing.JToggleButton btnHomePlayer5;
    private javax.swing.JToggleButton btnHomePlayer6;
    private javax.swing.JToggleButton btnHomePlayer7;
    private javax.swing.JToggleButton btnHomePlayer8;
    private javax.swing.JToggleButton btnHomePlayer9;
    private javax.swing.JButton btnIncreaseTime;
    private javax.swing.JButton btnMiss;
    private javax.swing.JButton btnSevenMeterThrow;
    private javax.swing.JButton btnShot;
    private javax.swing.JButton btnShotSaved;
    private javax.swing.JToggleButton btnStartClock;
    private javax.swing.JButton btnSteal;
    private javax.swing.JToggleButton btnStopClock;
    private javax.swing.JButton btnThrowIn;
    private javax.swing.JToggleButton btnTimeOut;
    private javax.swing.JButton btnTurnover;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelAwayTeamName;
    private javax.swing.JLabel labelAwayTeamScore;
    private javax.swing.JLabel labelHomeTeamName;
    private javax.swing.JLabel labelHomeTeamScore;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelAwayPlayers;
    private javax.swing.JPanel panelAwayTeam;
    private javax.swing.JPanel panelGameClock;
    private javax.swing.JPanel panelHomePlayers;
    private javax.swing.JPanel panelHomeTeam;
    private javax.swing.JPanel panelOverview;
    private javax.swing.JPanel panelShotActions;
    private javax.swing.JTextField textFieldClock;
    // End of variables declaration//GEN-END:variables

    

    
    
    
}
