/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is.deb.ui;

import is.deb.dummyData.*;
import is.deb.gameControl.GameClock;
import is.deb.teams.*;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.TimeUnit;
import javax.swing.*;

/**
 * @author: Dagný Ósk Ragnarsdóttir, Birkir Pálmason og
 * Eva Dögg Steingrímsdóttir
 * @since: 17.02.2015
 * Viðmót sem gefur notandanum kleift að skrá framgang handboltaleiks
 */
public class ScoringUI extends javax.swing.JFrame {
    

    boolean isGameStarted = false;
    GameClock gameClock; 
    GameTimer gameTimer;
    Team homeTeam = new Team(new Haukar().getLeikmenn(),"Haukar");
    Team awayTeam = new Team(new FH().getLeikmenn(),"FH");
    Team[] teams = new Team[]{homeTeam,awayTeam};
    JLabel[] labelsTeams;
    JToggleButton[] buttonsHomePlayers;
    JToggleButton[] buttonsAwayPlayers;
    private int teamWithBall = 0;
    private String time;
    private String liveFeed = "Velkomin/n";
    private final List<Suspension> homeSuspensions = new ArrayList<>();
    private final List<Suspension> awaySuspensions = new ArrayList<>();
    private int numberOfSuspensions = 0;
    private final int numberOfPlayers = 14;
    

    /**
     * Creates new form ScoringUI
     */
    public ScoringUI() {
        initComponents();
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setGUIObjects();
    }
    
    /**
     * Upphafsstillir viðmótshluti
     */
    private void setGUIObjects() {
        
        labelsTeams = new JLabel[]{labelHomeTeamScore,labelAwayTeamScore};
        buttonsHomePlayers = new JToggleButton[]{btnHomePlayer0,btnHomePlayer1,btnHomePlayer2,
        btnHomePlayer3,btnHomePlayer4,btnHomePlayer5,btnHomePlayer6,btnHomePlayer7,
        btnHomePlayer8,btnHomePlayer9,btnHomePlayer10,btnHomePlayer11,btnHomePlayer12,
        btnHomePlayer13};
        
        buttonsAwayPlayers = new JToggleButton[]{btnAwayPlayer0,btnAwayPlayer1,btnAwayPlayer2,
        btnAwayPlayer3,btnAwayPlayer4,btnAwayPlayer5,btnAwayPlayer6,btnAwayPlayer7,
        btnAwayPlayer8,btnAwayPlayer9,btnAwayPlayer10,btnAwayPlayer11,btnAwayPlayer12,
        btnAwayPlayer13};
        
        panelShotActions.setVisible(false);
        panelHomeSuspensions.setLayout(new BoxLayout(panelHomeSuspensions, BoxLayout.Y_AXIS));
        panelAwaySuspensions.setLayout(new BoxLayout(panelAwaySuspensions, BoxLayout.Y_AXIS));
        
    }
    
    /**
     * Setur nöfn leikmanna á JToggleButton viðmótshluti
     * @param team
     * @param playerButtons 
     */
    private void addPlayersToButtons(Team team,JToggleButton[] playerButtons) {
        for(int i = 0; i<playerButtons.length; i++) {
            Player player = team.getPlayerAtArrayPosition(i);
            if(player.isPlaying()) {
                String name = player.getPlayerName();
                int number = player.getPlayerNumber();
                playerButtons[i].setText(name + "" + " " + "(" + number + ")");
            }
        }
    }
    
    /**
     * Skilar fylki sem inniheldur heimaliðið í sæti 0 og liði gestanna
     * í sæti 1
     * @return 
     */
    public Team[] getTeams() {
        return teams;
    }
    
    /**
     * Breyta sem heldur utan um liðin sem að spila fær gildið 
     * newTeams
     * @param newTeams 
     */
    public void setPlayers(Team[] newTeams) {
        teams = newTeams;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOverview = new javax.swing.JPanel();
        panelGameClock = new javax.swing.JPanel();
        textFieldClock = new javax.swing.JTextField();
        btnDecreaseTime = new javax.swing.JButton();
        btnStartClock = new javax.swing.JToggleButton();
        btnStopClock = new javax.swing.JToggleButton();
        btnHalfTime = new javax.swing.JToggleButton();
        btnIncreaseTime = new javax.swing.JButton();
        btnTimeOut = new javax.swing.JToggleButton();
        panelHomeTeam = new javax.swing.JPanel();
        labelHomeTeamName = new javax.swing.JLabel();
        labelHomeTeamScore = new javax.swing.JLabel();
        panelAwayTeam = new javax.swing.JPanel();
        labelAwayTeamScore = new javax.swing.JLabel();
        labelAwayTeamName = new javax.swing.JLabel();
        panelHomePlayers = new javax.swing.JPanel();
        btnHomePlayer0 = new javax.swing.JToggleButton();
        btnHomePlayer1 = new javax.swing.JToggleButton();
        btnHomePlayer2 = new javax.swing.JToggleButton();
        btnHomePlayer3 = new javax.swing.JToggleButton();
        btnHomePlayer4 = new javax.swing.JToggleButton();
        btnHomePlayer5 = new javax.swing.JToggleButton();
        btnHomePlayer6 = new javax.swing.JToggleButton();
        btnHomePlayer7 = new javax.swing.JToggleButton();
        btnHomePlayer8 = new javax.swing.JToggleButton();
        btnHomePlayer9 = new javax.swing.JToggleButton();
        btnHomePlayer10 = new javax.swing.JToggleButton();
        btnHomePlayer12 = new javax.swing.JToggleButton();
        btnHomePlayer11 = new javax.swing.JToggleButton();
        btnHomePlayer13 = new javax.swing.JToggleButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelActions = new javax.swing.JPanel();
        btnShot = new javax.swing.JButton();
        btnFoul = new javax.swing.JButton();
        btnAssist = new javax.swing.JButton();
        btnTurnover = new javax.swing.JButton();
        btnThrowIn = new javax.swing.JButton();
        btnCorner = new javax.swing.JButton();
        btnSteal = new javax.swing.JButton();
        btnSevenMeterThrow = new javax.swing.JButton();
        btnFreeThrow = new javax.swing.JButton();
        btnGoalSave = new javax.swing.JButton();
        btnGoalSave1 = new javax.swing.JButton();
        btnGoalSave2 = new javax.swing.JButton();
        btnTwoMinutes = new javax.swing.JButton();
        panelShotActions = new javax.swing.JPanel();
        btnGoal = new javax.swing.JButton();
        btnMiss = new javax.swing.JButton();
        btnShotSaved = new javax.swing.JButton();
        panelAwayPlayers = new javax.swing.JPanel();
        btnAwayPlayer0 = new javax.swing.JToggleButton();
        btnAwayPlayer1 = new javax.swing.JToggleButton();
        btnAwayPlayer2 = new javax.swing.JToggleButton();
        btnAwayPlayer3 = new javax.swing.JToggleButton();
        btnAwayPlayer4 = new javax.swing.JToggleButton();
        btnAwayPlayer5 = new javax.swing.JToggleButton();
        btnAwayPlayer6 = new javax.swing.JToggleButton();
        btnAwayPlayer7 = new javax.swing.JToggleButton();
        btnAwayPlayer8 = new javax.swing.JToggleButton();
        btnAwayPlayer9 = new javax.swing.JToggleButton();
        btnAwayPlayer10 = new javax.swing.JToggleButton();
        btnAwayPlayer11 = new javax.swing.JToggleButton();
        btnAwayPlayer12 = new javax.swing.JToggleButton();
        btnAwayPlayer13 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaLiveFeed = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaStat = new javax.swing.JTextArea();
        panelHomeSuspensions = new javax.swing.JPanel();
        panelAwaySuspensions = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        textFieldClock.setEditable(false);
        textFieldClock.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        textFieldClock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldClock.setText("00:00");

        btnDecreaseTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecreaseTimeActionPerformed(evt);
            }
        });

        btnStartClock.setText("Play");
        btnStartClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartClockActionPerformed(evt);
            }
        });

        btnStopClock.setText("Pause");
        btnStopClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopClockActionPerformed(evt);
            }
        });

        btnHalfTime.setText("Hálfleikur");
        btnHalfTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHalfTimeActionPerformed(evt);
            }
        });

        btnIncreaseTime.setPreferredSize(new java.awt.Dimension(97, 29));
        btnIncreaseTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncreaseTimeActionPerformed(evt);
            }
        });

        btnTimeOut.setText("Leikhlé");
        btnTimeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGameClockLayout = new javax.swing.GroupLayout(panelGameClock);
        panelGameClock.setLayout(panelGameClockLayout);
        panelGameClockLayout.setHorizontalGroup(
            panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameClockLayout.createSequentialGroup()
                .addComponent(textFieldClock, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGameClockLayout.createSequentialGroup()
                        .addComponent(btnDecreaseTime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStartClock, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGameClockLayout.createSequentialGroup()
                        .addComponent(btnIncreaseTime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHalfTime, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimeOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStopClock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelGameClockLayout.setVerticalGroup(
            panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameClockLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldClock)
                    .addGroup(panelGameClockLayout.createSequentialGroup()
                        .addGroup(panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIncreaseTime, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnHalfTime, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGameClockLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(panelGameClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                    .addComponent(btnStartClock, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                    .addComponent(btnStopClock, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)))
                            .addGroup(panelGameClockLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDecreaseTime, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        panelHomeTeam.setPreferredSize(new java.awt.Dimension(151, 38));

        labelHomeTeamName.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelHomeTeamName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHomeTeamName.setPreferredSize(new java.awt.Dimension(119, 26));

        labelHomeTeamScore.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelHomeTeamScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelHomeTeamLayout = new javax.swing.GroupLayout(panelHomeTeam);
        panelHomeTeam.setLayout(panelHomeTeamLayout);
        panelHomeTeamLayout.setHorizontalGroup(
            panelHomeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelHomeTeamName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeTeamLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelHomeTeamScore, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelHomeTeamLayout.setVerticalGroup(
            panelHomeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeTeamLayout.createSequentialGroup()
                .addComponent(labelHomeTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHomeTeamScore, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelAwayTeam.setPreferredSize(new java.awt.Dimension(151, 38));

        labelAwayTeamScore.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelAwayTeamScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelAwayTeamName.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelAwayTeamName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelAwayTeamLayout = new javax.swing.GroupLayout(panelAwayTeam);
        panelAwayTeam.setLayout(panelAwayTeamLayout);
        panelAwayTeamLayout.setHorizontalGroup(
            panelAwayTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAwayTeamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAwayTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAwayTeamLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelAwayTeamScore, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAwayTeamLayout.createSequentialGroup()
                        .addComponent(labelAwayTeamName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelAwayTeamLayout.setVerticalGroup(
            panelAwayTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAwayTeamLayout.createSequentialGroup()
                .addComponent(labelAwayTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(labelAwayTeamScore, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout panelOverviewLayout = new javax.swing.GroupLayout(panelOverview);
        panelOverview.setLayout(panelOverviewLayout);
        panelOverviewLayout.setHorizontalGroup(
            panelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOverviewLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(panelHomeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(panelGameClock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(panelAwayTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(823, Short.MAX_VALUE))
        );
        panelOverviewLayout.setVerticalGroup(
            panelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOverviewLayout.createSequentialGroup()
                .addGroup(panelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelAwayTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelOverviewLayout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(panelHomeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelOverviewLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(panelGameClock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        btnHomePlayer0.setBorderPainted(false);
        btnHomePlayer0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer0ActionPerformed(evt);
            }
        });

        btnHomePlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer1ActionPerformed(evt);
            }
        });

        btnHomePlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer2ActionPerformed(evt);
            }
        });

        btnHomePlayer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer3ActionPerformed(evt);
            }
        });

        btnHomePlayer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer4ActionPerformed(evt);
            }
        });

        btnHomePlayer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer5ActionPerformed(evt);
            }
        });

        btnHomePlayer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer6ActionPerformed(evt);
            }
        });

        btnHomePlayer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer7ActionPerformed(evt);
            }
        });

        btnHomePlayer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer8ActionPerformed(evt);
            }
        });

        btnHomePlayer9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer9ActionPerformed(evt);
            }
        });

        btnHomePlayer10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer10ActionPerformed(evt);
            }
        });

        btnHomePlayer12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer12ActionPerformed(evt);
            }
        });

        btnHomePlayer11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer11ActionPerformed(evt);
            }
        });

        btnHomePlayer13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlayer13ActionPerformed(evt);
            }
        });

        jLayeredPane1.setBackground(new java.awt.Color(255, 51, 0));

        btnShot.setText("Skot");
        btnShot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShotActionPerformed(evt);
            }
        });

        btnFoul.setText("Brot");

        btnAssist.setText("Stoðsending");

        btnTurnover.setText("Tapaður bolti");

        btnThrowIn.setText("Innkast");

        btnCorner.setText("Horn");

        btnSteal.setText("Stolinn bolti");

        btnSevenMeterThrow.setText("Víti");

        btnFreeThrow.setText("Aukakast");

        btnGoalSave.setText("Markvarsla");

        btnGoalSave1.setText("Gult spjald");

        btnGoalSave2.setText("Rautt spjald");

        btnTwoMinutes.setText("2 mín");
        btnTwoMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoMinutesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActionsLayout = new javax.swing.GroupLayout(panelActions);
        panelActions.setLayout(panelActionsLayout);
        panelActionsLayout.setHorizontalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTwoMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelActionsLayout.createSequentialGroup()
                        .addComponent(btnGoalSave, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGoalSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnGoalSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelActionsLayout.createSequentialGroup()
                        .addComponent(btnFoul, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTurnover, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnSteal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelActionsLayout.createSequentialGroup()
                        .addComponent(btnShot, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSevenMeterThrow, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFreeThrow, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelActionsLayout.createSequentialGroup()
                        .addComponent(btnAssist, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThrowIn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnCorner, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelActionsLayout.setVerticalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShot, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSevenMeterThrow, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFreeThrow, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFoul, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTurnover, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSteal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssist, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThrowIn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCorner, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGoalSave, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoalSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoalSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTwoMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelShotActions.setBackground(new java.awt.Color(204, 0, 204));

        btnGoal.setText("Mark");
        btnGoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoalActionPerformed(evt);
            }
        });

        btnMiss.setText("Framhjá");
        btnMiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissActionPerformed(evt);
            }
        });

        btnShotSaved.setText("Varið");
        btnShotSaved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShotSavedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelShotActionsLayout = new javax.swing.GroupLayout(panelShotActions);
        panelShotActions.setLayout(panelShotActionsLayout);
        panelShotActionsLayout.setHorizontalGroup(
            panelShotActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShotActionsLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(panelShotActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShotSaved, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        panelShotActionsLayout.setVerticalGroup(
            panelShotActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShotActionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnShotSaved, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(444, 444, 444))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelShotActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(panelActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(panelShotActions, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );
        jLayeredPane1.setLayer(panelActions, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panelShotActions, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnAwayPlayer0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer0ActionPerformed(evt);
            }
        });

        btnAwayPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer1ActionPerformed(evt);
            }
        });

        btnAwayPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer2ActionPerformed(evt);
            }
        });

        btnAwayPlayer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer3ActionPerformed(evt);
            }
        });

        btnAwayPlayer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer4ActionPerformed(evt);
            }
        });

        btnAwayPlayer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer5ActionPerformed(evt);
            }
        });

        btnAwayPlayer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer6ActionPerformed(evt);
            }
        });

        btnAwayPlayer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer7ActionPerformed(evt);
            }
        });

        btnAwayPlayer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer8ActionPerformed(evt);
            }
        });

        btnAwayPlayer9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer9ActionPerformed(evt);
            }
        });

        btnAwayPlayer10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer10ActionPerformed(evt);
            }
        });

        btnAwayPlayer11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer11ActionPerformed(evt);
            }
        });

        btnAwayPlayer12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer12ActionPerformed(evt);
            }
        });

        btnAwayPlayer13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlayer13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAwayPlayersLayout = new javax.swing.GroupLayout(panelAwayPlayers);
        panelAwayPlayers.setLayout(panelAwayPlayersLayout);
        panelAwayPlayersLayout.setHorizontalGroup(
            panelAwayPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAwayPlayersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelAwayPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAwayPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer0, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAwayPlayer13, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelAwayPlayersLayout.setVerticalGroup(
            panelAwayPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAwayPlayersLayout.createSequentialGroup()
                .addComponent(btnAwayPlayer0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAwayPlayer13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        textAreaLiveFeed.setColumns(20);
        textAreaLiveFeed.setRows(5);
        jScrollPane1.setViewportView(textAreaLiveFeed);

        javax.swing.GroupLayout panelHomePlayersLayout = new javax.swing.GroupLayout(panelHomePlayers);
        panelHomePlayers.setLayout(panelHomePlayersLayout);
        panelHomePlayersLayout.setHorizontalGroup(
            panelHomePlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomePlayersLayout.createSequentialGroup()
                .addGroup(panelHomePlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHomePlayer12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer13, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer0, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomePlayer11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelHomePlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomePlayersLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelHomePlayersLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(panelAwayPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHomePlayersLayout.setVerticalGroup(
            panelHomePlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomePlayersLayout.createSequentialGroup()
                .addGroup(panelHomePlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomePlayersLayout.createSequentialGroup()
                        .addGroup(panelHomePlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHomePlayersLayout.createSequentialGroup()
                                .addComponent(btnHomePlayer0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnHomePlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnHomePlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnHomePlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnHomePlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnHomePlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnHomePlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnHomePlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnHomePlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnHomePlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(btnHomePlayer10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(panelHomePlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelHomePlayersLayout.createSequentialGroup()
                                .addComponent(btnHomePlayer11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnHomePlayer12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnHomePlayer13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelAwayPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        textAreaStat.setColumns(20);
        textAreaStat.setRows(5);
        jScrollPane2.setViewportView(textAreaStat);

        jMenu1.setText("File");
        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelHomeSuspensions, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(panelHomePlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAwaySuspensions, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelOverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelHomePlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addComponent(panelHomeSuspensions, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(panelAwaySuspensions, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Leiktíminn er stöðvaður
     * @param evt 
     */
    private void btnHalfTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHalfTimeActionPerformed
        gameTimer.timer.stop();
    }//GEN-LAST:event_btnHalfTimeActionPerformed

    /**
     * Leiktíminn (og niðurteljari á brottvísunum ef einhverjar eru) er settur
     * af stað
     * @param evt 
     */
    private void btnStartClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartClockActionPerformed
        if(!isGameStarted) {
            gameClock = new GameClock();
            isGameStarted = true;
            gameTimer = new GameTimer();
            time = gameClock.getGameTimeString();
            updateLiveFeed("Leikurinn er hafinn");
        }
        gameTimer.timer.start();
        startSuspensions(homeSuspensions);
        startSuspensions(awaySuspensions);
        
        if(btnStartClock.isSelected()) {
            btnStopClock.setSelected(false);
        }
    }//GEN-LAST:event_btnStartClockActionPerformed

    /**
     * Leiktíminn (og niðurteljari á brottvísunum ef einhverjar eru) er 
     * stöðvaður
     * @param evt 
     */
    private void btnStopClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopClockActionPerformed
        gameTimer.timer.stop(); 
        if(btnStopClock.isSelected()) {
            btnStartClock.setSelected(false);
        }
        pauseSuspensions(homeSuspensions);
        pauseSuspensions(awaySuspensions);
    }//GEN-LAST:event_btnStopClockActionPerformed

    /**
     * Niðurtalning á brottvísunum er stöðvuð
     * @param suspensions 
     */
    private void pauseSuspensions(List<Suspension> suspensions) {
        suspensions.stream().forEach((suspension) -> {
            suspension.timer.stop();
        });
    }
    
    /**
     *  Niðurtalning á brottvísunum er sett af stað
     * @param suspensions 
     */
    private void startSuspensions(List<Suspension> suspensions) {
        suspensions.stream().forEach((suspension) -> {
            suspension.timer.start();
        });
    }
    
    /**
     * Kallað er á aðferð sem að tekur eina sekúndu af leiktímanum
     * @param evt 
     */
    private void btnDecreaseTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecreaseTimeActionPerformed
        changeGameClock("decrease");
    }//GEN-LAST:event_btnDecreaseTimeActionPerformed

    /**
     * Leiktíminn (og niðurteljari á brottvísunum ef einhverjar eru) er
     * stöðvaður
     * @param evt 
     */
    private void btnTimeOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeOutActionPerformed
        time = gameClock.getGameTimeString();
        timeout(); 
    }//GEN-LAST:event_btnTimeOutActionPerformed

    /**
     * Kallað er á aðferð sem að bætir einnu sekúndu við leiktímann
     * @param evt 
     */
    private void btnIncreaseTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncreaseTimeActionPerformed
        changeGameClock("increase");
    }//GEN-LAST:event_btnIncreaseTimeActionPerformed

    /**
     * Kallar á aðferð sem að bætir nýju marki við fylki allra marka hjá því
     * liði sem skoraði og á aðferð sem að bætir einu marki við þann leikmann
     * sem að skoraði. Uppfærir textalýsingu
     * @param evt 
     */
    private void btnGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoalActionPerformed
        teams[teamWithBall].newGoal(time,getCurrentPlayer(teamWithBall).
                getPlayerNumber());
        getCurrentPlayer(teamWithBall).goal();
        labelsTeams[teamWithBall].setText(teams[teamWithBall].getScore()+"");
        updateShotAction("Mark");
    }//GEN-LAST:event_btnGoalActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 0 í fylki allra leikmanna
     * í heimaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnHomePlayer0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer0ActionPerformed
        setCurrentPlayer(0,buttonsHomePlayers);
    }//GEN-LAST:event_btnHomePlayer0ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 1 í fylki allra leikmanna
     * í heimaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnHomePlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer1ActionPerformed
        setCurrentPlayer(1,buttonsHomePlayers);
    }//GEN-LAST:event_btnHomePlayer1ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 2 í fylki allra leikmanna
     * í heimaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnHomePlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer2ActionPerformed
        setCurrentPlayer(2,buttonsHomePlayers);
    }//GEN-LAST:event_btnHomePlayer2ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 3 í fylki allra leikmanna
     * í heimaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnHomePlayer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer3ActionPerformed
        setCurrentPlayer(3,buttonsHomePlayers);
    }//GEN-LAST:event_btnHomePlayer3ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 4 í fylki allra leikmanna
     * í heimaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnHomePlayer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer4ActionPerformed
        setCurrentPlayer(4,buttonsHomePlayers);
    }//GEN-LAST:event_btnHomePlayer4ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 5 í fylki allra leikmanna
     * í heimaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnHomePlayer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer5ActionPerformed
        setCurrentPlayer(5,buttonsHomePlayers);
    }//GEN-LAST:event_btnHomePlayer5ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 6 í fylki allra leikmanna
     * í heimaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnHomePlayer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer6ActionPerformed
        setCurrentPlayer(6,buttonsHomePlayers);
    }//GEN-LAST:event_btnHomePlayer6ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 7 í fylki allra leikmanna
     * í heimaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnHomePlayer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer7ActionPerformed
        setCurrentPlayer(7,buttonsHomePlayers);
    }//GEN-LAST:event_btnHomePlayer7ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 8 í fylki allra leikmanna
     * í heimaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnHomePlayer8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer8ActionPerformed
        setCurrentPlayer(8,buttonsHomePlayers);
    }//GEN-LAST:event_btnHomePlayer8ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 9 í fylki allra leikmanna
     * í heimaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnHomePlayer9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer9ActionPerformed
        setCurrentPlayer(9,buttonsHomePlayers);
    }//GEN-LAST:event_btnHomePlayer9ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 10 í fylki allra leikmanna
     * í heimaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnHomePlayer10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer10ActionPerformed
        setCurrentPlayer(10,buttonsHomePlayers);
    }//GEN-LAST:event_btnHomePlayer10ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 11 í fylki allra leikmanna
     * í heimaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnHomePlayer11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer11ActionPerformed
        setCurrentPlayer(11,buttonsHomePlayers);
    }//GEN-LAST:event_btnHomePlayer11ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 12 í fylki allra leikmanna
     * í heimaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnHomePlayer12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer12ActionPerformed
        setCurrentPlayer(12,buttonsHomePlayers);
    }//GEN-LAST:event_btnHomePlayer12ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 13 í fylki allra leikmanna
     * í heimaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnHomePlayer13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlayer13ActionPerformed
        setCurrentPlayer(13,buttonsHomePlayers);
    }//GEN-LAST:event_btnHomePlayer13ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 0 í fylki allra leikmanna
     * í gestaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnAwayPlayer0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer0ActionPerformed
        setCurrentPlayer(0,buttonsAwayPlayers);
    }//GEN-LAST:event_btnAwayPlayer0ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 1 í fylki allra leikmanna
     * í gestaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnAwayPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer1ActionPerformed
        setCurrentPlayer(1,buttonsAwayPlayers);
    }//GEN-LAST:event_btnAwayPlayer1ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 2 í fylki allra leikmanna
     * í gestaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnAwayPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer2ActionPerformed
        setCurrentPlayer(2,buttonsAwayPlayers);
    }//GEN-LAST:event_btnAwayPlayer2ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 3 í fylki allra leikmanna
     * í gestaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnAwayPlayer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer3ActionPerformed
        setCurrentPlayer(3,buttonsAwayPlayers);
    }//GEN-LAST:event_btnAwayPlayer3ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 4 í fylki allra leikmanna
     * í gestaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnAwayPlayer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer4ActionPerformed
        setCurrentPlayer(4,buttonsAwayPlayers);
    }//GEN-LAST:event_btnAwayPlayer4ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 5 í fylki allra leikmanna
     * í gestaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnAwayPlayer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer5ActionPerformed
        setCurrentPlayer(5,buttonsAwayPlayers);
    }//GEN-LAST:event_btnAwayPlayer5ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 6 í fylki allra leikmanna
     * í gestaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnAwayPlayer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer6ActionPerformed
        setCurrentPlayer(6,buttonsAwayPlayers);
    }//GEN-LAST:event_btnAwayPlayer6ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 7 í fylki allra leikmanna
     * í gestaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnAwayPlayer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer7ActionPerformed
        setCurrentPlayer(7,buttonsAwayPlayers);
    }//GEN-LAST:event_btnAwayPlayer7ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 8 í fylki allra leikmanna
     * í gestaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnAwayPlayer8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer8ActionPerformed
        setCurrentPlayer(8,buttonsAwayPlayers);
    }//GEN-LAST:event_btnAwayPlayer8ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 9 í fylki allra leikmanna
     * í gestaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnAwayPlayer9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer9ActionPerformed
        setCurrentPlayer(9,buttonsAwayPlayers);
    }//GEN-LAST:event_btnAwayPlayer9ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 10 í fylki allra leikmanna
     * í gestaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnAwayPlayer10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer10ActionPerformed
        setCurrentPlayer(10,buttonsAwayPlayers);
    }//GEN-LAST:event_btnAwayPlayer10ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 11 í fylki allra leikmanna
     * í gestaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnAwayPlayer11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer11ActionPerformed
        setCurrentPlayer(11,buttonsAwayPlayers);
    }//GEN-LAST:event_btnAwayPlayer11ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 12 í fylki allra leikmanna
     * í gestaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnAwayPlayer12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer12ActionPerformed
        setCurrentPlayer(12,buttonsAwayPlayers);
    }//GEN-LAST:event_btnAwayPlayer12ActionPerformed

    /**
     * LKallar á aðferð sem að gerir leikmann í sæti 13 í fylki allra leikmanna
     * í gestaliðinu að þeim leikmanni sem er með boltann
     * @param evt 
     */
    private void btnAwayPlayer13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlayer13ActionPerformed
        setCurrentPlayer(13,buttonsAwayPlayers);
    }//GEN-LAST:event_btnAwayPlayer13ActionPerformed

    /**
     * Sér til þess að aðeins einn leikmaður getur verið sá leikmaður sem er
     * með boltann í einu. Gerir leikmann í sæti buttonPosition að þeim leikmanni
     * @param buttonPosition
     * @param team 
     */
    public void setCurrentPlayer(int buttonPosition, JToggleButton[] team) {
        for (int i = 0; i<numberOfPlayers; i++) {
            if (buttonsHomePlayers[i].isSelected()) {
                buttonsHomePlayers[i].setSelected(false);
            }
            if (buttonsAwayPlayers[i].isSelected()) {
                buttonsAwayPlayers[i].setSelected(false);
            }
        }
        team[buttonPosition].setSelected(true);
        if(Arrays.equals(team, buttonsHomePlayers)) {
            teamWithBall = 0;
        }
        else {
            teamWithBall = 1;
        }
    }
    
    /**
     * Kallar á aðferð sem að uppfærir breytu sem að heldur utan um hvaða leikmaður
     * er með boltann gildi
     * @param evt 
     */
    private void btnShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShotActionPerformed
        panelActions.setVisible(false);
        panelShotActions.setVisible(true);
        time = gameClock.getGameTimeString();
        getCurrentPlayer(teamWithBall).shot();
    }//GEN-LAST:event_btnShotActionPerformed

    /**
     * Kallar á aðferð sem að uppfærir niðurstöður kasts með gildinu "Framhjá"
     * @param evt 
     */
    private void btnMissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissActionPerformed
        updateShotAction("Framhjá");
    }//GEN-LAST:event_btnMissActionPerformed

    /**
     * Uppfærir textalýsingu til að gefa til kynna að leimaður hafi skotið
     * og birtir viðmót þar sem hægt er að skrá niðurstöðu skotsins
     * @param action 
     */
    private void updateShotAction(String action) {
        time = gameClock.getGameTimeString();
        String newFeed = "(" + teams[teamWithBall].getTeamName() + ") " + 
                "Leikmaður númer " + getCurrentPlayer(teamWithBall).
                        getPlayerNumber()+
                " skot: " + action;
        updateLiveFeed(newFeed);
        panelShotActions.setVisible(false);
        panelActions.setVisible(true);
    }
    
    /**
     * Kallar á aðferð sem að uppfærir niðurstöður kasts með gildinu "Varið"
     * @param evt 
     */
    private void btnShotSavedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShotSavedActionPerformed
        updateShotAction("Varið");
    }//GEN-LAST:event_btnShotSavedActionPerformed

    /**
     * Uppfærir textalýsingu til að gefa til kynna að leimaður hafi fengið
     * tveggja mínútna brottvísun og kallar á aðferð sem að sér um að skrá
     * brottvísunina á tiltekinn leikmann
     * @param action 
     */
    private void btnTwoMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoMinutesActionPerformed
        time = gameClock.getGameTimeString();
        String newFeed = "(" + teams[teamWithBall].getTeamName() + ") " + 
                "Leikmaður númer " + getCurrentPlayer(teamWithBall).
                        getPlayerNumber()+
                " fékk 2 mín";
        updateLiveFeed(newFeed);
        teams[teamWithBall].twoMinutes(time,getCurrentPlayer(teamWithBall).
                getPlayerNumber());
        getCurrentPlayer(teamWithBall).twoMinutes();
        setSuspensions();
    }//GEN-LAST:event_btnTwoMinutesActionPerformed

    /**
     * Birtir niðurtalningu fyrir nýja tveggja mínutna brottvísun í 
     * viðmótinu
     */
    private void setSuspensions() {
        javax.swing.JLabel label = new javax.swing.JLabel("labelSuspension"+
                numberOfSuspensions);
        label.setText("");
        Suspension suspension = new Suspension(label,teamWithBall);
        if(teamWithBall==0) {
            panelHomeSuspensions.add(label);
            homeSuspensions.add(suspension);
        }
        else {
            panelAwaySuspensions.add(label);
            awaySuspensions.add(suspension);
        }
        numberOfSuspensions++;
        pack();
    }
    
    /**
     * Upphafsstillir viðmótið með viðeigandi liði með því að kalla á 
     * aðferð sem sér um að setja nöfn leikmanna.
     * @param evt 
     */
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        addPlayersToButtons(teams[0],buttonsHomePlayers);
        addPlayersToButtons(teams[1],buttonsAwayPlayers);
        labelHomeTeamName.setText(teams[0].getTeamName());
        labelAwayTeamName.setText(teams[1].getTeamName());
    }//GEN-LAST:event_formWindowActivated

    /**
     * Skilar þeim leikmanni sem er skráður með boltann
     * @param team
     * @return 
     */
    public Player getCurrentPlayer(int team) {
        if(team==0) {
            return findCurrentPlayer(buttonsHomePlayers, homeTeam);
        }
        else {
            return findCurrentPlayer(buttonsAwayPlayers, awayTeam);
        }
    }
    
    /**
     * Skilar þeim leikmanni sem er skráður með boltann (Hjálparfall fyrir
     * getCurrentPlayer)
     * @param buttonTeam
     * @param team
     * @return 
     */
    public Player findCurrentPlayer(JToggleButton[] buttonTeam, Team team ) {
        for(int i = 0; i<buttonTeam.length; i++) {
            if(buttonTeam[i].isSelected()) {
                return team.getPlayer(i);
            }
        }
        
        return null;
    }
    
    /**
     * Uppfærir textalýsingu
     * @param feed 
     */
    private void updateLiveFeed(String feed) {
        liveFeed = liveFeed + "\n" + time + ": " + feed;
        textAreaLiveFeed.setText(liveFeed);
    }
    
    /**
     * Sér um að stöðva tímann á brottvísunum þegar leikhlé er tekið
     * og setja hann aftur á þegar leikhlé er búið.
     */
    public void timeout() {
        if(btnTimeOut.isSelected()) {
            gameTimer.timer.stop();
            updateLiveFeed("Leikhlé");
            pauseSuspensions(homeSuspensions);
            pauseSuspensions(awaySuspensions);
            
        }
        else {
            gameTimer.timer.start();
            updateLiveFeed("Leikhéi lokið");
            startSuspensions(homeSuspensions);
            startSuspensions(awaySuspensions);
        }
    }
    
    /**
     * Breytir leiktímanum
     * @param action 
     */
    private void changeGameClock(String action) {
        if("decrease".equals(action)) {
            gameClock.decreaseSeconds();
        }
        else {
            gameClock.increaseSeconds();
        }
        textFieldClock.setText(gameClock.getGameTimeString());
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoringUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoringUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoringUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoringUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ScoringUI().setVisible(true);
                try {
            // Set cross-platform Java L&F (also called "Metal")
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
    } 
    catch (     UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException e) {
       // handle exception
    }
                // handle exception
                // handle exception
                // handle exception

                
                
            }
        });
    }
    
    /**
    * @author: Dagný Ósk Ragnarsdóttir, Birkir Pálmason og
    * Eva Dögg Steingrímsdóttir
    * @since: 17.02.2015
    * Klasinn sér um að leiktíminn sé uppfærður á einna sekúnda fresti
    */
    public class GameTimer {
        private final Timer timer; 
        
        /**
         * Býr til nýjan hlut af taginu GameTimer
         */
        public GameTimer() {
            timer = new Timer(1000, new TimerListener());
            timer.start();
        }
        
        /**
         * Hlustari fyrir GameTimer
         */
        private class TimerListener implements ActionListener {
            @Override
            /**
             * Uppfærir leiktímann um eina sekúndu og birtir nýjan tíma
             * í viðmótinu
             */
            public void actionPerformed(ActionEvent e) {
                gameClock.increaseSeconds();
                textFieldClock.setText(gameClock.getGameTimeString());
            }
        }
    }
    
    /**
    * @author: Dagný Ósk Ragnarsdóttir, Birkir Pálmason og
    * Eva Dögg Steingrímsdóttir
    * @since: 17.02.2015
    * Klasinn sér um að tími brottvísana sé uppfærður á einna sekúnda fresti
    */
    public class Suspension {
        private final Timer timer; 
        private int seconds;
        JLabel label;
        private final int team;
        
        /**
         * Býr til nýja brottvísun
         * @param label
         * @param team 
         */
        public Suspension(JLabel label,int team) {
            timer = new Timer(1000, new TimerListener());
            timer.start();
            this.label = label;
            this.team = team;
        }
        
        /**
         * Hlustari fyrir Suspenson hlut
         */
        private class TimerListener implements ActionListener {
            @Override
            
            /**
             * Uppfærir tíma brottvísunar um eina sekúndu og birtir nýjan tíma
             * í viðmótinu ef 2 mínútur eru ekki liðnar.
             */
            public void actionPerformed(ActionEvent e) {
                if(seconds==120) {
                    timer.stop();
                    if(team==0) {
                        homeSuspensions.remove(0);
                        panelHomeSuspensions.remove(label);
                        panelHomeSuspensions.revalidate();
                        panelHomeSuspensions.repaint();
                    }
                    else {
                        awaySuspensions.remove(0);
                        panelAwaySuspensions.remove(label);
                        panelAwaySuspensions.revalidate();
                        panelAwaySuspensions.repaint();
                    }
                     
                }
                else {
                    seconds++;
                }
                label.setText(getSuspensionTimeString(120-seconds));
            }
        }
        
        public String getSuspensionTimeString(int gameTimeSeconds) {
            return String.format("%02d:%02d", 
            TimeUnit.SECONDS.toMinutes(gameTimeSeconds),
            TimeUnit.SECONDS.toSeconds(gameTimeSeconds) - 
            TimeUnit.MINUTES.toSeconds(TimeUnit.SECONDS.toMinutes(gameTimeSeconds)));
        
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssist;
    private javax.swing.JToggleButton btnAwayPlayer0;
    private javax.swing.JToggleButton btnAwayPlayer1;
    private javax.swing.JToggleButton btnAwayPlayer10;
    private javax.swing.JToggleButton btnAwayPlayer11;
    private javax.swing.JToggleButton btnAwayPlayer12;
    private javax.swing.JToggleButton btnAwayPlayer13;
    private javax.swing.JToggleButton btnAwayPlayer2;
    private javax.swing.JToggleButton btnAwayPlayer3;
    private javax.swing.JToggleButton btnAwayPlayer4;
    private javax.swing.JToggleButton btnAwayPlayer5;
    private javax.swing.JToggleButton btnAwayPlayer6;
    private javax.swing.JToggleButton btnAwayPlayer7;
    private javax.swing.JToggleButton btnAwayPlayer8;
    private javax.swing.JToggleButton btnAwayPlayer9;
    private javax.swing.JButton btnCorner;
    private javax.swing.JButton btnDecreaseTime;
    private javax.swing.JButton btnFoul;
    private javax.swing.JButton btnFreeThrow;
    private javax.swing.JButton btnGoal;
    private javax.swing.JButton btnGoalSave;
    private javax.swing.JButton btnGoalSave1;
    private javax.swing.JButton btnGoalSave2;
    private javax.swing.JToggleButton btnHalfTime;
    private javax.swing.JToggleButton btnHomePlayer0;
    private javax.swing.JToggleButton btnHomePlayer1;
    private javax.swing.JToggleButton btnHomePlayer10;
    private javax.swing.JToggleButton btnHomePlayer11;
    private javax.swing.JToggleButton btnHomePlayer12;
    private javax.swing.JToggleButton btnHomePlayer13;
    private javax.swing.JToggleButton btnHomePlayer2;
    private javax.swing.JToggleButton btnHomePlayer3;
    private javax.swing.JToggleButton btnHomePlayer4;
    private javax.swing.JToggleButton btnHomePlayer5;
    private javax.swing.JToggleButton btnHomePlayer6;
    private javax.swing.JToggleButton btnHomePlayer7;
    private javax.swing.JToggleButton btnHomePlayer8;
    private javax.swing.JToggleButton btnHomePlayer9;
    private javax.swing.JButton btnIncreaseTime;
    private javax.swing.JButton btnMiss;
    private javax.swing.JButton btnSevenMeterThrow;
    private javax.swing.JButton btnShot;
    private javax.swing.JButton btnShotSaved;
    private javax.swing.JToggleButton btnStartClock;
    private javax.swing.JButton btnSteal;
    private javax.swing.JToggleButton btnStopClock;
    private javax.swing.JButton btnThrowIn;
    private javax.swing.JToggleButton btnTimeOut;
    private javax.swing.JButton btnTurnover;
    private javax.swing.JButton btnTwoMinutes;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAwayTeamName;
    private javax.swing.JLabel labelAwayTeamScore;
    private javax.swing.JLabel labelHomeTeamName;
    private javax.swing.JLabel labelHomeTeamScore;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelAwayPlayers;
    private javax.swing.JPanel panelAwaySuspensions;
    private javax.swing.JPanel panelAwayTeam;
    private javax.swing.JPanel panelGameClock;
    private javax.swing.JPanel panelHomePlayers;
    private javax.swing.JPanel panelHomeSuspensions;
    private javax.swing.JPanel panelHomeTeam;
    private javax.swing.JPanel panelOverview;
    private javax.swing.JPanel panelShotActions;
    private javax.swing.JTextArea textAreaLiveFeed;
    private javax.swing.JTextArea textAreaStat;
    private javax.swing.JTextField textFieldClock;
    // End of variables declaration//GEN-END:variables

    

    
    
    
}
